package com.example.fastorder.auth.di

import android.content.Context
import androidx.credentials.CredentialManager
import com.example.fastorder.BuildConfig
import com.example.fastorder.R
import com.example.fastorder.auth.data.FirebaseAuthRepository
import com.example.fastorder.auth.data.GoogleCredentialClient
import com.example.fastorder.auth.domain.AuthRepository
import com.example.fastorder.di.ApplicationScope
import com.google.firebase.auth.FirebaseAuth
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent
import kotlinx.coroutines.CoroutineScope
import timber.log.Timber
import javax.inject.Singleton

/**
 * Bindings for the `auth` feature slice.
 *
 * Lives inside `auth/` rather than in the app-level `di/` package so the slice
 * owns its own wiring. Extracting `:feature:auth` later is then a directory
 * move: the module travels with the code it constructs, and the app module -
 * which only ever sees the [AuthRepository] interface - needs no edit at all.
 *
 * Everything here is `@Singleton` because a session is a process-wide fact.
 * Two [AuthRepository] instances would mean two auth-state listeners and two
 * answers to "am I signed in?", which is exactly the bug the single seam
 * exists to prevent.
 */
@Module
@InstallIn(SingletonComponent::class)
object AuthModule {

    @Provides
    @Singleton
    fun provideFirebaseAuth(): FirebaseAuth = FirebaseAuth.getInstance().apply {
        // Debug builds only - the flag is hard-coded false for release.
        //
        // Skips the reCAPTCHA-config probe and the Play Integrity round trip
        // that together account for most of the delay between tapping "Send
        // code" and the code pane appearing. Test numbers still work; real
        // numbers stop working, which is the trade and why it is opt-out.
        if (BuildConfig.DISABLE_PHONE_APP_VERIFICATION) {
            firebaseAuthSettings.setAppVerificationDisabledForTesting(true)
            Timber.w("Auth: phone app-verification DISABLED - test numbers only")
        }
    }

    /**
     * The single [AuthRepository] for the process.
     *
     * [FirebaseAuthRepository] and [GoogleCredentialClient] are `internal` and
     * deliberately stay that way - they are constructed here rather than bound
     * as separate `@Provides`, so the Firebase and Credential Manager types
     * never appear in a signature anything outside `auth/data` can see.
     *
     * @param externalScope must outlive any screen. A `viewModelScope` here
     *   would cancel the auth-state subscription the moment the sign-in screen
     *   left - precisely when the resulting session matters most.
     */
    @Provides
    @Singleton
    fun provideAuthRepository(
        firebaseAuth: FirebaseAuth,
        @ApplicationContext context: Context,
        @ApplicationScope externalScope: CoroutineScope,
    ): AuthRepository = FirebaseAuthRepository(
        firebaseAuth = firebaseAuth,
        googleCredentialClient = GoogleCredentialClient(
            credentialManager = CredentialManager.create(context),
            // Generated by the Google Services Gradle plugin from the
            // `client_type: 3` OAuth entry in google-services.json. Reading it
            // from resources rather than hard-coding means rotating the client,
            // or pointing at a different Firebase project, is a matter of
            // dropping in a new google-services.json.
            //
            // Note for the eventual :feature:auth split: this `R` belongs to
            // the app module, because that is where the Google Services plugin
            // is applied. The value would then be passed in from the app
            // module instead - one binding to move, not a redesign.
            serverClientId = context.getString(R.string.default_web_client_id),
        ),
        externalScope = externalScope,
    )
}

